form:
  validation: loose

  fields:
    dropdown.enabled:
      type: toggle
      label: MUNDANA.ADMIN.THEME.DROPDOWN_MENU
      highlight: 1
      default: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool    
    production-mode:
      type: toggle
      label: MUNDANA.ADMIN.THEME.PRODUCTION_MODE
      help: MUNDANA.ADMIN.THEME.PRODUCTION_MODE_HELP
      highlight: 1
      default: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool
    back_to_top_button:
      type: toggle
      label: MUNDANA.ADMIN.THEME.BACK_TO_TOP_BUTTON
      help: MUNDANA.ADMIN.THEME.BACK_TO_TOP_BUTTON_HELP
      highlight: 1
      default: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool
    header_section:
      type: section
      title: MUNDANA.ADMIN.THEME.HEADER_OPTIONS
      underline: true
    favicon:
      type: file
      label: MUNDANA.ADMIN.THEME.FAVICON
      description: MUNDANA.ADMIN.THEME.FAVICON_DESCRIPTION
      destination: 'theme@:/images'
      multiple: false
      avoid_overwriting: false
      random_name: false
      toggleable: true
      filesize: 3
      accept: ['image/png', '.ico']
    custom_logo_enabled:
      type: toggle
      label: MUNDANA.ADMIN.THEME.CUSTOM_LOGO.ENABLED
      help: MUNDANA.ADMIN.THEME.CUSTOM_LOGO.ENABLED_HELP
      highlight: 1
      default: 1
      options:
          1: PLUGIN_ADMIN.ENABLED
          0: PLUGIN_ADMIN.DISABLED
      validate:
          type: bool
    custom_logo_width:
      type: number
      size: small
      default: 100
      validate:
        min: 20
        max: 300
      label: MUNDANA.ADMIN.THEME.CUSTOM_LOGO.WIDTH
    custom_logo:
      type: file
      label: MUNDANA.ADMIN.THEME.CUSTOM_LOGO.FILE
      size: large
      destination: 'theme://images/logo'
      multiple: false
      markdown: true
      description: MUNDANA.ADMIN.THEME.CUSTOM_LOGO.DESCRIPTION
      accept:
        - image/*
    custom_logo_mobile:
      type: file
      label: MUNDANA.ADMIN.THEME.CUSTOM_LOGO.FILE_MOBILE
      size: large
      destination: 'theme://images/logo'
      multiple: false
      accept:
        - image/*
    google_fonts_local:
      type: toggle
      label: MUNDANA.ADMIN.THEME.GOOGLE_FONTS_LOCAL
      highlight: 0
      default: 0
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool
    font_awesome_local:
      type: toggle
      label: MUNDANA.ADMIN.THEME.FONT_AWESOME_LOCAL
      highlight: 0
      default: 0
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool
    bootstrap_local:
      type: toggle
      label: MUNDANA.ADMIN.THEME.BOOTSTRAP_LOCAL
      highlight: 0
      default: 0
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool
    custom_css:
      type: toggle
      label: MUNDANA.ADMIN.THEME.CUSTOM_CSS
      help: MUNDANA.ADMIN.THEME.CUSTOM_CSS_HELP
      highlight: 1
      default: true
      options:
        1: Enabled
        0: Disabled
    custom_js:
      type: toggle
      label: MUNDANA.ADMIN.THEME.CUSTOM_JS
      help: MUNDANA.ADMIN.THEME.CUSTOM_JS_HELP
      highlight: 1
      default: true
      options:
        1: Enabled
        0: Disabled
    menu_options:
      type: section 
      title: MUNDANA.ADMIN.THEME.MENU.TITLE
      underline: true
    menu_langswitcher:
      type: toggle
      label: MUNDANA.ADMIN.THEME.MENU.LANGSWITCHER
      help: MUNDANA.ADMIN.THEME.MENU.LANGSWITCHER_HELP
      default: 1
      highlight: 1
      options:
          1: PLUGIN_ADMIN.ENABLED
          0: PLUGIN_ADMIN.DISABLED
      validate:
          type: bool
    
    menu_search:
      type: toggle
      label: MUNDANA.ADMIN.THEME.MENU.SEARCH
      help: MUNDANA.ADMIN.THEME.MENU.SEARCH_HELP
      default: 1
      highlight: 1
      options:
          1: PLUGIN_ADMIN.ENABLED
          0: PLUGIN_ADMIN.DISABLED
      validate:
          type: bool
    
    menu_login:
      type: toggle
      label: MUNDANA.ADMIN.THEME.MENU.LOGIN
      help: MUNDANA.ADMIN.THEME.MENU.LOGIN_HELP
      default: 1
      highlight: 1
      options:
          1: PLUGIN_ADMIN.ENABLED
          0: PLUGIN_ADMIN.DISABLED
      validate:
          type: bool
    page_style_options:
      type: section
      title: MUNDANA.ADMIN.THEME.PAGE_STYLE.TITLE
      underline: true
    override_page_style:
      type: toggle
      label: MUNDANA.ADMIN.THEME.PAGE_STYLE.OVERRIDE_PAGE_STYLE
      help: MUNDANA.ADMIN.THEME.PAGE_STYLE.OVERRIDE_PAGE_STYLE_HELP
      highlight: 0
      default: 0
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool
    default_page_style:
      type: select
      label: MUNDANA.ADMIN.THEME.PAGE_STYLE.LABEL
      help: MUNDANA.ADMIN.THEME.PAGE_STYLE.HELP
      description: MUNDANA.ADMIN.THEME.PAGE_STYLE.DESCRIPTION
      size: medium
      toggleable: true
      data-options@: '\Grav\Theme\Mundana::getPageStyles'
    navbar_options:
      type: section
      title: MUNDANA.ADMIN.THEME.NAVBAR.OPTIONS
      underline: true
    navbar.container_fluid:
      type: toggle
      label: MUNDANA.ADMIN.THEME.NAVBAR.CONTAINER_FLUID
      help: MUNDANA.ADMIN.THEME.NAVBAR.CONTAINER_FLUID_HELP
      highlight: 0
      default: 0
      options:  
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool
    navbar.height:
      type: number
      size: small
      default: 70
      validate:
        min: 35
        max: 150
      label: MUNDANA.ADMIN.THEME.NAVBAR.HEIGHT
    navbar.display_site_name:
      type: toggle
      label: MUNDANA.ADMIN.THEME.NAVBAR.DISPLAY_SITE_NAME
      help: MUNDANA.ADMIN.THEME.NAVBAR.DISPLAY_SITE_NAME_HELP
      highlight: 1
      default: 1
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool
    navbar.icon:
      type: text
      label: MUNDANA.ADMIN.THEME.NAVBAR.ICON
      help: MUNDANA.ADMIN.THEME.NAVBAR.ICON_HELP
      description: MUNDANA.ADMIN.THEME.NAVBAR.ICON_DESCRIPTION
      size: medium
      toggleable: true
    navbar.icon_group:
      type: select
      label: MUNDANA.ADMIN.THEME.NAVBAR.ICON_GROUP
      size: small
      default: fab
      options:
        fas: fas
        fa: fa
        fab: fab
    navbar.icon_size:
      type: select
      label: MUNDANA.ADMIN.THEME.NAVBAR.ICON_SIZE
      size: small
      default: ''
      options:
        '': default
        fa-xs: xs
        fa-sm: sm
        fa-lg: lg
    navbar.style:
      type: select
      size: small
      label: MUNDANA.ADMIN.THEME.NAVBAR.STYLE.LABEL
      help: MUNDANA.ADMIN.THEME.NAVBAR.STYLE.HELP
      default: light
      options:
        dark: MUNDANA.ADMIN.THEME.NAVBAR.STYLE.LIGHT
        light: MUNDANA.ADMIN.THEME.NAVBAR.STYLE.DARK
    navbar.bgcolor:
      type: select
      size: small
      label: MUNDANA.ADMIN.THEME.NAVBAR.BGCOLOR
      help:
      data-options@: '\Grav\Theme\Mundana::getPageStyles' 
    navbar.custom_bgcolor:
      type: colorpicker
      label: MUNDANA.ADMIN.THEME.NAVBAR.CUSTOM_BGCOLOR
      help:
      toggleable: true
      size: small
      default: '#ffffff'
    custom_menu:
      type: section         
      title: MUNDANA.ADMIN.THEME.CUSTOM_MENU.TITLE
      underline: true           
    custom_menu_enabled:
      type: toggle
      label: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ENABLED.LABEL
      help: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ENABLED.HELP
      default: 0
      highlight: 0
      options:
        1: PLUGIN_ADMIN.ENABLED
        0: PLUGIN_ADMIN.DISABLED
      validate:
        type: bool
    custom_menu_items:
      name: menu
      type: list
      collapsed: true
      label: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ITEMS.LABEL
      fields:
        .text:
          type: text
          label: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ITEMS.TEXT
          description: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ITEMS.TEXT_DESCRIPTION
        .icon:
          type: text
          label: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ITEMS.ICON
          description: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ITEMS.ICON_DESCRIPTION
        .url:
          type: text
          label: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ITEMS.URL
          description: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ITEMS.URL_DESCRIPTION
        .target:
          type: select
          label: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ITEMS.TARGET.LABEL
          default: _self
          size: medium
          options:
            _blank: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ITEMS.TARGET.BLANK
            _parent: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ITEMS.TARGET.PARENT
            _top: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ITEMS.TARGET.TOP
            _self: MUNDANA.ADMIN.THEME.CUSTOM_MENU.ITEMS.TARGET.SELF